### ISSUE TITLE
Awsome Script! I have a couple questions.

### ISSUE THREAD

**Issue by smitchell6879** [sanghviharshit/script.kodi.lifx.ambilight#10]
First off this is a awesome addon and it works 99% of the time easy to setup love it. 

So the issue is at random I will get:

03:18:12.152 T:5280   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'i' referenced before assignment
                                            Traceback (most recent call last) File "C:\Users\USERNAME\Desktop\Metadata\portable_data\addons\script.kodi.lifx.ambilight\default.py", line 512, in <module>
                                                run()
                                              File "C:\Users\USERNAME\Desktop\Metadata\portable_data\addons\script.kodi.lifx.ambilight\default.py", line 339, in run
                                                hsvRatios = screen.spectrum_hsv(screen.pixels, screen.capture_width, screen.capture_height)
                                              File "C:\Users\USERNAME\Desktop\Metadata\portable_data\addons\script.kodi.lifx.ambilight\default.py", line 276, in spectrum_hsv
                                                if int(i) != 0:
                                            UnboundLocalError: local variable 'i' referenced before assignment
                                            -->End of Python script error report<--

Not exact sure when this is being used so I am not sure where to start looking to solve this issue.

Second I have edited the one line to allow this to work with episodes as well. My question to you if you will help I would like to set the l.get_current_setting() from within kodi. My question is how would I set that up? 

I see in the debug log your sending 
DEBUG: Kodi Lifx: DEBUG light Entertainment: onLast: True, briLast: 32
04:06:50.299 T:1396   DEBUG: Kodi Lifx: DEBUG set_light2: Entertainment: {"hue": 56855, "kel": 3500, "on": false, "transitiontime": 4, "bri": 44, "sat": 93}

I am just no quite understanding how this is being translated to the bulb just yet.

If you have time and don't might pointing me in the right direction I would gladly appreciate your time.

Best Regards,
Steven

**Comment by tree718** [comment]
I'm trying to download a lifx ambilight to my Kodi box how do I go about doing that I have the lifx Z LED strips behind my TV and I've been dying to set them up so that whatever movies playing it matches the colors please help me

**Comment by sanghviharshit** [comment]
@smitchell6879 the bug should be fixed in latest version of the addon.
@tree718 Go to https://bit.ly/kodilifx for step by step installation instructions. This is an addon for Kodi media center. Check out https://kodi.tv/ for instructions on setting it up first.

**Comment by tree718** [comment]
I thank you so much for the information when I get a chance I'm going to
start to work look it up and see how it works cuz I was to the point where
I was going to have to get Philips Hue Lights but the lifx strips are more
in detailed color than Philips Hue

**Comment by sanghviharshit** [comment]
You are welcome :)

**Comment by tree718** [comment]
I do have to figure out how to configure it to my Nvidia Shield or on the
built of Kodi
