### ISSUE TITLE
Lifx z led strips

### ISSUE THREAD

**Issue by tree718** [sanghviharshit/script.kodi.lifx.ambilight#11]
Can somebody tell me how to set up the lifx Z LED strips to my Nvidia Shield to work on my Kodi for ambilight

**Comment by sanghviharshit** [comment]
I need to update the liflan module, addon should work with z strip after that.

**Comment by sanghviharshit** [comment]
This is fixed in the new version 0.1.2. Please let me know if you still find any issues after updating it to 0.1.2. Technically the addon should auto update.

**Comment by tree718** [comment]
What program do I download to make it work with the either TV or my Kodi I
have an Nvidia Shield and I have Kodi download it onto that

**Comment by tree718** [comment]
Is there a URL or is it file I can open up to download that on to the Kodi
program
