### ISSUE TITLE
No longer discovers Gen 2 bulbs on firmware v1.22 (lifxlan library out of date?)

### ISSUE THREAD

**Issue by bamzero** [sanghviharshit/script.kodi.lifx.ambilight#12]
Have just updated my bulb firmware to v1.22 and found the addon can no longer discover these bulbs, though still discovers my original Gen 1 bulbs ok. Other apps (android etc) are able to discover all bulbs ok.

I'm guessing this may be resolved by updating the addon to work with the latest lifxlan library (which in turn also supports lifx z strips, so may take care of two issues)

**Comment by sanghviharshit** [comment]
Ok, thanks for letting me know. I will fix it soon.

**Comment by bamzero** [comment]
I got it working again for my gen 2 bulbs by simply updating the lifxlan files. At first I thought there was compatibility issues between them and the addon but it seems it has it's own problem for Windows.

I had to edit devices.py to just use a broadcast address of 255.255.255.255 rather than new Windows workaround of using the local subnet broadcast address ([thanks to this](https://github.com/mclarkk/lifxlan/issues/60)).

**Comment by vascozorrinho** [comment]
@bamzero can you send me the changed files please?

**Comment by bamzero** [comment]
@vascozorrinho You can find them here https://github.com/mclarkk/lifxlan

**Comment by sanghviharshit** [comment]
This is fixed in the new version 0.1.2. Please let me know if you still find any issues after updating it to 0.1.2. Technically the addon should auto update.
