### ISSUE TITLE
No bulbs detected

### ISSUE THREAD

**Issue by eangulus** [sanghviharshit/script.kodi.lifx.ambilight#14]
Just got 12 Lifx bulbs and got everything set up, and was hoping to use the 3 lounge room ones for Ambilight.

I installed this plugin but for some reason, it keeps saying that no bulbs are detected.

The bulbs are working fine with the Lifx App. They are Lifx Mini's if that matters.

I did try to adjust the broadcast IP value as per written in the Kodi forums to no avail.

**Comment by g3c2** [comment]
Same issue here. My lifx strip works with every application on my phone but not with this add-on.  I am running it from a physically connected PC, same network, same subnet - is that supposed to make a difference?

**Comment by eangulus** [comment]
No solution for me. At this stage, I cannot get any 3rd party apps, programs, scripts to work with Lifx Mini.

Really regretting my decision on Lifx now.

**Comment by g3c2** [comment]
Hm... I can get 3rd party apps working fine, just not this add-on.  One example I can offer you is "OnSwitch" (ios /free/App store) - just a simple scene app that picked up my lifx light right away.  That's what I used to narrow down connectivity probs to this add-on, unless it has something to do with my having connected via ethernet (which wouldn't make sense to me). g'luck...

**Comment by eangulus** [comment]
But what type of bulbs? I seem to read a lot of issues with 3rd party stuff for the new Mini's. I don't see problems with the older bulbs.

**Comment by eangulus** [comment]
And I have tried Onswitch on a Pixel XL.

Nothing at all. Not 1 single bulb out of the 12 I have here.

**Comment by g3c2** [comment]
Hi I have the Lifx Z Experience model LZC3M4WWUC07 / 10ft

**Comment by eangulus** [comment]
Does that use a different API?

I think the Mini uses v3

**Comment by sanghviharshit** [comment]
New version `v1` should work with Lifx Z and Lifx Mini.
