### ISSUE TITLE
Question for 3 bulbs

### ISSUE THREAD

**Issue by apat183** [sanghviharshit/script.kodi.lifx.ambilight#16]
I have three (ceiling) bulbs and want to have them all same. I've selected in settings to have all bulbs same color but they still different colors. 

Am I doing something wrong? What does the color bias do? Do I need to set this to 36 to have the most accuracy to make them all match? I notice two of them are normally match but the third one is off. Also whats the difference between the new and old algorithm?

Thanks. Sorry know it's not issue.

**Comment by sanghviharshit** [comment]
I'm about to release a newer version which is a complete rework of the addon and should resolve most of the existing issues. Do you mind testing it from the latest `develop` branch and let me know if you see any major issues? It has more intuitive settings for `color bias` and `color variation` which can help you set up same colors for all your lights.

**Comment by apat183** [comment]
Yep I can try over the weekend and let you know how it goes.

**Comment by sanghviharshit** [comment]
Great! Thanks :)
