### ISSUE TITLE
Not working on Kodi 18 Nightly

### ISSUE THREAD

**Issue by xnisyaj** [sanghviharshit/script.kodi.lifx.ambilight#17]
Hi! The ambilight mode is not working in Kodi 18 nightly version, the theatre mode works fine, but on ambilight mode it just fades the lights and keep it dark. Tested with local video, Quasar plugin, and latest plugin.video.netflix, same case every time. I'm using the nightly 18 version because its the only one that supports the new netflix plugin. (macOS) 

Thanks!

**Comment by sanghviharshit** [comment]
I'm about to release a newer version which is a complete rework of the addon and should resolve most of the existing issues. Do you mind testing it from the latest `develop` branch and let me know if you see any major issues?
