### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by jmdish** [sanghviharshit/script.kodi.lifx.ambilight#24]
Hi all,
i'm not sure if i can post here. First of all, excuse my bad language as  - first i'm French, - second i'm not a Dev.
I use your plugin for months and thanks a lot it is great !
I get this error with the kodi plugin, but only with one type of bulb.
I have lifx mini (49) and lifx mini white (50).
With lifx mini, it work like i want : I use the theater method just to dim the light.
with lifx mini white, the light doesn't dim.
In kodi.log i get:
*****
19:11:36.039 T:6800   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: int() argument must be a string or a number, not 'NoneType'
                                            Traceback (most recent call last):
                                              File "C:\Users\JMD\AppData\Roaming\Kodi\addons\script.kodi.lifx.ambilight\default.py", line 114, in onPlayBackStarted
                                                state_changed("started", self.duration)
                                              File "C:\Users\JMD\AppData\Roaming\Kodi\addons\script.kodi.lifx.ambilight\default.py", line 299, in state_changed
                                                hue.theater_controller.on_playback_start(resume)
                                              File "C:\Users\JMD\AppData\Roaming\Kodi\addons\script.kodi.lifx.ambilight\resources\lib\theater_controller.py", line 41, in on_playback_start
                                                force_on=self.settings.force_light_on,
                                              File "C:\Users\JMD\AppData\Roaming\Kodi\addons\script.kodi.lifx.ambilight\resources\lib\lights.py", line 215, in set_state
                                                transition_time=transition_time
                                              File "C:\Users\JMD\AppData\Roaming\Kodi\addons\script.kodi.lifx.ambilight\resources\lib\lights.py", line 124, in set_state
                                                color = [int(state['hue']),int(state['sat']*257),int(state['bri']*257),int(state['kel'])]
                                            TypeError: int() argument must be a string or a number, not 'NoneType'
                                            -->End of Python script error report<--
****
Note that if i change the bulb for lifx mini (49); it works again and no more error.
the difference between 2 is:
                49: {"color": True,
                     "temperature": True,
                     "infrared": False,
                     "multizone": False},
                50: {"color": False,
                     "temperature": False,
                     "infrared": False,
                     "multizone": False},
I guess the white might return a bad value but i don't know where to search.
Thx a lot if you can help. Ask if you need further informations.
JMD

**Comment by sanghviharshit** [comment]
This is the perfect place to report any issues with the addon. You did a good job providing the `Exception` message from the log. I will try to find out the root cause based on what the information you provided and fix it. I will let you know if I need more details or logs.

**Comment by jmdish** [comment]
ok thx a lot. I forgot, i did the tests on kodi 17.6 with the plugin last branch dev on windows 7. But at term, this will run on android TV. I don't know if this is important.
I must confess i read all the py files, commenting a line from time to time but with no success.
As we say (at least in France): "better one who knows than hundred who search" 
good luck ;)

**Comment by jmdish** [comment]
Hi,
It Works ! (as may say an Apache server ^^).
I just change theses two lines in "lights.py:
****
24        self.fullspectrum = True # All Lifx Color bulbs are fullspectrum
25        self.livingwhite = False
****
to force fullspectrum.
With mini white,
if you ask supports_color(), it say False; but if you ask get_color(), you get HSBK (0,0,65535,2703).
Just to be safe, I overwrite HUE in theater mode to 24910 but it works without that.
Seems to be the "Livingwhite" way that bug.
Hope this help.
JMD

**Comment by sanghviharshit** [comment]
Thanks for the update. This bug should have been resolved now with the latest release version 1.0.2
