### ISSUE TITLE
Plugin crashing on Apple tv 4k

### ISSUE THREAD

**Issue by hycel78** [sanghviharshit/script.kodi.lifx.ambilight#26]
Kodi 17.6 on apple tv 4k
version 1.0.0 was the last working version. 
Since then the plugin crashes on start. Last tested version 1.0.3

![img_8198](https://user-images.githubusercontent.com/34385540/38774562-80166490-4031-11e8-9184-1defab281a65.jpg)
![img_8199](https://user-images.githubusercontent.com/34385540/38774563-843a5284-4031-11e8-9a16-017df62c606f.jpg)

**Comment by sanghviharshit** [comment]
Can you please turn debug logging on and then reproduce the issue, so I can get information about your current settings and some context when it failed? 
To record the logs, go to settings wheel -> System settings -> Logging -> Enable Debug Logging and follow the procedure at http://kodi.wiki/view/Log_file/Easy

**Comment by sanghviharshit** [comment]
Thanks for reporting the bug, I have found the issue and fixing it shortly.
