### ISSUE TITLE
Discovery of Lifx lights doesn't work (error in log) 

### ISSUE THREAD

**Issue by hycel78** [sanghviharshit/script.kodi.lifx.ambilight#28]
In the log i see the plugin has my lights that i've set up when it was still on 1.0.0 version. With then new 1.0.5 version plugin throws an error when trying to discover lights. Also throws an error when trying to setup theater, ambilight or static lights.
Error present on both apple tv4k kodi 17.6 and amlogic box running libreelec with kodi 17.6

here's the log:
https://paste.kodi.tv/etanucuqud

**Comment by sanghviharshit** [comment]
Thank you for being so patient and reporting the issues. Fixing it now
