### ISSUE TITLE
Lights don't dim on initial playback - Kodi v18RC1

### ISSUE THREAD

**Issue by paulnd** [sanghviharshit/script.kodi.lifx.ambilight#32]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] feedback

* **If the current behavior is a bug, please provide the steps to reproduce**
Start playback, pause and then resume

  * **What is the current behavior?**
Light don't dim on initial playback, only after pausing and then resuming. This occurs for each new playback.

  * **What is the expected behavior?**
Lights should dim on initial playback

  * **(Important) Logs**
    * _(Follow https://github.com/sanghviharshit/script.kodi.lifx.ambilight/wiki/Logs for sharing link to logs)_
https://pastebin.com/5Dzvu2iP

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  - Kodi Version v18 RC1
  - Addon Version: 1.06
  - OS: Windows 10
  - Lifx Devices:

* **Other information**
  * _(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc.)_

**Comment by paulnd** [comment]
Hello,

Is this something that could be fixed please? 

The same occurs with RC3 and I've also noticed that the lights don't return when play back stops, they only return if I stop in the OSD

**Comment by paulnd** [comment]
https://forum.kodi.tv/showthread.php?tid=334929

**Comment by sanghviharshit** [comment]
Release 1.0.7. Should auto update soon.
