### ISSUE TITLE
Ambilight don't work (LifX A19 Gen3 - Kodi 18 #Leia)

### ISSUE THREAD

**Issue by dimitrij2k** [sanghviharshit/script.kodi.lifx.ambilight#36]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] feedback

Ambilight don't change light to frame color. Fixed to a random color at the beginning with minimal brightness (default 30)

* **Please tell me about your environment:**
  - Kodi Version: 18 (Leia)
  - Addon Version: 1.0.7
  - OS: Shield TV (Android 8.0)
  - Lifx Devices: A19 (Gen3)

**Comment by sanghviharshit** [comment]
Try this - https://github.com/sanghviharshit/script.kodi.lifx.ambilight/wiki/Known-Issues
