### ISSUE TITLE
Hardcode bulbs?

### ISSUE THREAD

**Issue by edent** [sanghviharshit/script.kodi.lifx.ambilight#4]
Loving this! Is there any way I can edit the settings to specify which two bulbs I want to act as ambilights?

I don't need the one in my bathroom pulsing away ;-)

**Comment by sanghviharshit** [comment]
Absolutely. Please take a look at my response to similar use case - http://forum.kodi.tv/showthread.php?tid=289230&pid=2409783#pid2409783

**Comment by sanghviharshit** [comment]
I have updated Readme as well - https://github.com/sanghviharshit/script.kodi.lifx.ambilight/blob/master/README.md#settings-for-specific-use-cases
