### ISSUE TITLE
Restore from Ambilight / Color Accuracy

### ISSUE THREAD

**Issue by eidermar** [sanghviharshit/script.kodi.lifx.ambilight#5]
Now that I was able to overcome my VPN broadcasting problems, I was finally able to test this. You did some great work here.

Now two things I had trouble with:

1. The light group that is in Ambilight mode doesn't restore to previous color & brightness. Bulbs that operate in theater mode only do this properly.

2. This is the more important Issue. The Ambilight mode is very jumpy and inconsistent with my screens colors/brightness. I tried every possible combination of threshold and brightness settings but was unable to get a decent result. It almost seems as if the sample for the dominant color is chosen to narrow and hence jumps around wildly even with minimal changes in the scene. I was using this [https://github.com/mhtsbt/kodi-lifx](https://github.com/mhtsbt/kodi-lifx) until now and although it lacks a lot of features and has some bugs, the Ambilight implementation seems to work much better. Maybe you could investigate his code to determine the dominant screen color and see if there is some inspiration for an improvement?

Thanks a lot for sharing your hard work with us.

**Comment by tree718** [comment]
Can somebody please help me to download a lifx ambilight to my Nvidia Shield to work on my Kodi

**Comment by sanghviharshit** [comment]
@eidermar Thanks for reporting the issues. I have improved the algorithm in the latest release 0.1.2 and should fix the jumpiness in ambilight mode. Also, With this version, the lights in ambilight mode should also return to original state after video is stopped. Let me know if you still find any issues.

**Comment by tree718** [comment]
So can I still hook it up through Cody or can I hook it up through my
Samsung TV I wish you can be through my Samsung TV Direct why don't they
have programs like that
