### ISSUE TITLE
Bulbs detected, not working

### ISSUE THREAD

**Issue by quentinf33** [sanghviharshit/script.kodi.lifx.ambilight#7]
When I install the plugin, a notification says that 1 bulb discovered, but when I start a video, it stays off. I use the latest version of Kodi, and my bulb firmware is updated...

**Comment by sanghviharshit** [comment]
Can you share your settings for the addon? You can also take a look at settings for some of the common use cases here - https://github.com/sanghviharshit/script.kodi.lifx.ambilight/tree/develop#settings-for-specific-use-cases

**Comment by quentinf33** [comment]
It works now, but only 1 bulb is detected, instead of 2...

**Comment by sanghviharshit** [comment]
I will need the logs and screenshots of your settings in order to debug this. If you can control both bulbs from your Lifx app, both bulbs should be discovered by the addon.
