### ISSUE TITLE
python 

### ISSUE THREAD

**Issue by omittchi** [sanghviharshit/script.kodi.lifx.ambilight#8]
Is there a way to use this as just a python script running outside of kodi? I prefer to use mediaportal and mpc-hc instead of kodi, but would love to use this. Also, I read it's not working with lifx strip lighting? Is that in progress? Would be awesome to put a strip lifx around the projector screen. Thanks!

**Comment by sanghviharshit** [comment]
I don't think so as this addon relies on some of the features that Kodi provides such as taking screen captures and events such as media playback and status.
